main:
  clusterGroupName: datacenter

global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  imageregistry:
    account: cl_snaps
    hostname: quay.io
    type: quay

  git:
    hostname: github.com
    account: cablelabs
    username: cablelabs
    email: a.kadam@cablelabs.com
    dev_revision: main

  s3:
    bucket:
      name: industrial-iot-bucket
      region: us-east-1
      message:
        aggregation:
          count: 50
      custom:
        endpoint:
          enabled: false
