apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-artifacts-rwo
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-external-storagecluster-cephfs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
